version: '3.7'

services:
  ms-gpt:
    build: 
      context: ./ms-gptLink-cesi
      dockerfile: Dockerfile
    container_name: ms-gptLink
    restart: unless-stopped
    env_file:
      - env/ms-gpt.env
    # ports:
    #   - "4002:4000"
    
  ms-chat:
    build:
      context: ./ms-chat-cesi
      dockerfile: Dockerfile
    container_name: ms-chat
    restart: unless-stopped
    env_file:
      - env/ms-chat.env
    # ports:
    #   - "4001:4000"

  ms-gateway:
    build:
      context: ./ms-gateway-cesi
      dockerfile: Dockerfile
    container_name: ms-gateway
    restart: unless-stopped
    env_file:
      - env/ms-gateway.env
    ports:
      - "4000:4000"
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - env/mongodb.env
    # ports:
    #   - "27017:27017"
    volumes:
      - dataMongoDb:/data/db

  ms-frontend:
    build:
      context: ./ms-frontend-gpt-cesi
      dockerfile: Dockerfile
    container_name: ms-frontend
    restart: unless-stopped
    env_file:
      - env/frontend.env
    ports:
      - "80:80"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - env/mongoExpress.env
  
volumes:
  dataMongoDb: {}